/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSucursalesRouteImport } from './routes/_authenticated/sucursales'
import { Route as AuthenticatedRelojesRouteImport } from './routes/_authenticated/relojes'
import { Route as AuthenticatedEmpleadosRouteImport } from './routes/_authenticated/empleados'
import { Route as AuthenticatedAsistenciasRouteImport } from './routes/_authenticated/asistencias'

const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/_authenticated/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSucursalesRoute = AuthenticatedSucursalesRouteImport.update({
  id: '/_authenticated/sucursales',
  path: '/sucursales',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRelojesRoute = AuthenticatedRelojesRouteImport.update({
  id: '/_authenticated/relojes',
  path: '/relojes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEmpleadosRoute = AuthenticatedEmpleadosRouteImport.update({
  id: '/_authenticated/empleados',
  path: '/empleados',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAsistenciasRoute =
  AuthenticatedAsistenciasRouteImport.update({
    id: '/_authenticated/asistencias',
    path: '/asistencias',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/asistencias': typeof AuthenticatedAsistenciasRoute
  '/empleados': typeof AuthenticatedEmpleadosRoute
  '/relojes': typeof AuthenticatedRelojesRoute
  '/sucursales': typeof AuthenticatedSucursalesRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesByTo {
  '/asistencias': typeof AuthenticatedAsistenciasRoute
  '/empleados': typeof AuthenticatedEmpleadosRoute
  '/relojes': typeof AuthenticatedRelojesRoute
  '/sucursales': typeof AuthenticatedSucursalesRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/asistencias': typeof AuthenticatedAsistenciasRoute
  '/_authenticated/empleados': typeof AuthenticatedEmpleadosRoute
  '/_authenticated/relojes': typeof AuthenticatedRelojesRoute
  '/_authenticated/sucursales': typeof AuthenticatedSucursalesRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/asistencias' | '/empleados' | '/relojes' | '/sucursales' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/asistencias' | '/empleados' | '/relojes' | '/sucursales' | '/'
  id:
    | '__root__'
    | '/_authenticated/asistencias'
    | '/_authenticated/empleados'
    | '/_authenticated/relojes'
    | '/_authenticated/sucursales'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedAsistenciasRoute: typeof AuthenticatedAsistenciasRoute
  AuthenticatedEmpleadosRoute: typeof AuthenticatedEmpleadosRoute
  AuthenticatedRelojesRoute: typeof AuthenticatedRelojesRoute
  AuthenticatedSucursalesRoute: typeof AuthenticatedSucursalesRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sucursales': {
      id: '/_authenticated/sucursales'
      path: '/sucursales'
      fullPath: '/sucursales'
      preLoaderRoute: typeof AuthenticatedSucursalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/relojes': {
      id: '/_authenticated/relojes'
      path: '/relojes'
      fullPath: '/relojes'
      preLoaderRoute: typeof AuthenticatedRelojesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/empleados': {
      id: '/_authenticated/empleados'
      path: '/empleados'
      fullPath: '/empleados'
      preLoaderRoute: typeof AuthenticatedEmpleadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/asistencias': {
      id: '/_authenticated/asistencias'
      path: '/asistencias'
      fullPath: '/asistencias'
      preLoaderRoute: typeof AuthenticatedAsistenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedAsistenciasRoute: AuthenticatedAsistenciasRoute,
  AuthenticatedEmpleadosRoute: AuthenticatedEmpleadosRoute,
  AuthenticatedRelojesRoute: AuthenticatedRelojesRoute,
  AuthenticatedSucursalesRoute: AuthenticatedSucursalesRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
